### ISSUE TITLE
TxpowerFix - HT Mode Bug?

### ISSUE THREAD

**Issue by AKA-47** [eulenfunk/packages#1]
Moin... Was passiert denn wenn ich auf kanal 12 bin?
Es sollte dann doch HT40- werden und nicht HT40 +

--- determine HT-Mode direction
channel = uci:get('wireless', interface24, 'channel')
if channel == '13' then
        htMode = 'HT40-'
elseif channel == '11' then
        htMode = 'HT40-'
else
        htMode = 'HT40+'
end

**Comment by Adorfer** [comment]
gefixt. (hatte ich nicht mit gerechnet, dass jemand Kanal12 nimmt)

**Comment by AKA-47** [comment]
Fix ist aber bisher nur im Upgrade script. Die andere Datei fehlt noch.

**Comment by Adorfer** [comment]
im anderen script leider ohne effekt, eigentlich könnte das alles raus. das "Bo" genau dort bringt ja leider auch nichts. 
Eben weil das Wifi nicht vollständig initialisiert ist.
