### ISSUE TITLE
wifi check don't reboot during the first hour

### ISSUE THREAD

**Issue by rubo77** [eulenfunk/packages#14]
I would add a check if the router is online at least one hour, otherwise, you can cause a reboot every 10 minutes if the wifi is really bad.

https://github.com/eulenfunk/packages/blob/v2016.2.x/gluon-wificheck/files/lib/gluon/wificheck/wificheck.sh

**Comment by Adorfer** [comment]
Please describe the scenario. 
(I understand  that "bad wifi" may occur. But why does it become better after the first hour? Is there a way to get to that state faster?)

**Comment by rubo77** [comment]
it makes no sense to reboot during the first one hour, but this could happen, for example, in an installation session, where you install several routers in a room and switch  lots of them off at the same time.

Even if a router gets the wifi-bug during the first few minutes already, you don't want to reboot it immediately. this can make it complicated to debug the scenario.

**Comment by rubo77** [comment]
I created a PR #17
