### ISSUE TITLE
TXpowerFix - always setting maximum TXPower after sysupgrade

### ISSUE THREAD

**Issue by AKA-47** [eulenfunk/packages#2]
After Sysupgrade and the one time call of /lib/gluon/txpowerfix/txpowerfix.lua via the /etc/init.d/txpowerfix the fix sets the region BO and the maximum TX Power.
This seems useless because building firmware with region BO generally solves the problem because the dropdown in configmode simply reads iwinfo client0(1) txpowerlist which then shows all values correctly.
The fix shoud better check that no more power than allowed is used instead of writing the maximum power via UCI to /etc/config/wireless.

otherwise a simple init script which checks if we are in config mode and set region BO should do the job. 
i dont think we really need decision of HT modes here because we dont switch wireless channels whithin luci.

**Comment by Adorfer** [comment]
HTmode is neccesary to have HT40 back again.

**Comment by Adorfer** [comment]
Im Setup-Mode bringt das alles nichts, auch nicht "BO" in der site.conf oder in dem script: Schlicht weil das Radio noch nicht initialisiert wurde wenn das Web-Setup gestartet wird.

**Comment by Adorfer** [comment]
Should be resolved meanwhile.
