### ISSUE TITLE
Das Skript 'nodeinfo' zeigt falsche Geokoordinaten an

### ISSUE THREAD

**Issue by oszilloskop** [eulenfunk/packages#5]
Das Skript ['nodeinfo' ](https://github.com/eulenfunk/packages/blob/master/gluon-banner/files/usr/bin/nodeinfo) zeigt für Latitude die Daten von Longitude an.

Ist:

```
echo -n " lat:$(uci show|grep .longitude=|cut -d= -f2)"
```

Soll:

```
echo -n " lat:$(uci show|grep .latitude =|cut -d= -f2)"
```

**Comment by viisauksena** [comment]
upsTream ist dies (glaube)und vieles mehr (auch svhwerwiegendere) gefixt,
Da das gerade hier nicht gemaintaint wird, als grundlage unbedingt 
viisauksena/gluon-banner
nehmen

**Comment by ghost** [comment]
Ja, das Paket hat nie wirklich funktioniert. Die Install-Scripts richten Mist an, sodass nach der Entfernung gar kein Banner mehr angezeigt wird und man eine standard Busybox-Shell bekommt..

**Comment by viisauksena** [comment]
ne das muss so - schau mal in etc/ ob da noch andere banner liegen, das script überschreibt diese ja 
- nochmal einige Skripte machen in dieser Version mist !

**Comment by Adorfer** [comment]
fixed
